FlaskApp/seotech_app/content/views.py
from flask import (
    request,
    render_template,
    flash,
    redirect,
    url_for,
    session,
    Blueprint,
    current_app as app,
)
from seotech_app.content.models import (
    Customer,
    NewsLetter,
    NewsLetterForm,
    CustomerMessageForm,
    get_mongo,
)


main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def home():
    mongo = get_mongo(app)
    form = CustomerMessageForm()
    newsform = NewsLetterForm()
    slider_data = []
    for slider in mongo.slider.find():
        slider_data.append(
            {
                "title": slider.get("title"),
                "description": slider.get("description"),
                "contact_link": slider.get("contact_link"),
                "quote_link": slider.get("quote_link"),
                "image": slider.get("image"),
                
            }
        )
    print(slider_data)

    about_data = []
    for about in mongo.about.find():
        about_data.append(
            {
                "title": about.get("title"),
                "description": about.get("description"),
                "image": about.get("image"),
            }
        )

    team_data = []
    for team in mongo.team.find():
        team_data.append(
            {
                "name": team.get("name"),
                "description": team.get("description"),
                "image": team.get("image"),
                "link_fb": team.get("link_fb"),
                "link_tw": team.get("link_tw"),
                "link_linkedin": team.get("link_linkedin"),
                "link_insta": team.get("link_insta"),
            }
        )
    work_data = []
    for work in mongo.work.find():
        work_data.append(
            {
                "title": work.get("title"),
                "description": work.get("description"),
                "service_title": work.get("service_title"),
                "service_description": work.get("service_description"),
                "read": work.get("read"),
                "image": work.get("image"),
            }
        )

    contact_data = []
    for contact in mongo.contact.find():
        contact_data.append(
            {
                "telephone": contact.get("telephone"),
                "email": contact.get("email"),
            }
        )
    client_data = []
    for client in mongo.clients.find():
        client_data.append(
            {
                "title": client.get("title"),
                "description": client.get("description"),
                "service_title": client.get("client_title"),
                "service_description": client.get("client_description"),
                "read": client.get("read"),
                "image": client.get("image"),
            }
        )
        for client in client_data:
            print("client image:", client["image"])
    service_data = []
    for service in mongo.service.find():
        service_data.append(
            {
                "title": service.get("title"),
                "description": service.get("description"),
                "service_title": service.get("service_title"),
                "service_description": service.get("service_description"),
                "read": service.get("read"),
                "image": service.get("image"),
            }
        )
        print(service.get("image"))
    footer_data = []
    for footer in mongo.footer.find():
        footer_data.append(
            {
                "title": footer.get("title"),
                "description": footer.get("description"),
                "link_facebook": footer.get("link_facebook"),
                "link_twitter": footer.get("link_twitter"),
                "link_linkedin": footer.get("link_linkedin"),
                "link_youtube": footer.get("link_youtube"),
            }
        )
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        subject = form.subject.data
        message = form.message.data
        customer = Customer(name, email, subject, message, mongo)
        customer.save()

        return redirect(url_for("main.home"))

    if newsform.validate_on_submit():
        email = newsform.email.data
        newsletter = NewsLetter(email, mongo)
        newsletter.save()

        return redirect(url_for("main.home"))

    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(
                    {"title": "Error", "message": f"Error in {field}:{error}"},
                    "error",
                )
    return render_template(
        "home.html",
        home="home",
        form=form,
        newsform=newsform,
        slider_data=slider_data,
        about_data=about_data,
        service_data=service_data,
        team_data=team_data,
        contact_data=contact_data,
        work_data=work_data,
        client_data=client_data,
        footer_data=footer_data,
    )


@main.route("/about", methods=["GET", "POST"])
def about():
    mongo = get_mongo(app)
    form = CustomerMessageForm()
    newsform = NewsLetterForm()
    about_data = []
    for about in mongo.about.find():
        about_data.append(
            {
                "title": about.get("title"),
                "description": about.get("description"),
                "image": about.get("image"),
            }
        )

    contact_data = []
    for contact in mongo.contact.find():
        contact_data.append(
            {
                "telephone": contact.get("telephone"),
                "email": contact.get("email"),
            }
        )

    footer_data = []
    for footer in mongo.footer.find():
        footer_data.append(
            {
                "title": footer.get("title"),
                "description": footer.get("description"),
                "link_facebook": footer.get("link_facebook"),
                "link_twitter": footer.get("link_twitter"),
                "link_linkedin": footer.get("link_linkedin"),
                "link_youtube": footer.get("link_youtube"),
            }
        )
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        subject = form.subject.data
        message = form.message.data
        customer = Customer(name, email, subject, message, mongo)
        customer.save()

        return redirect(url_for("main.home"))

    if newsform.validate_on_submit():
        email = newsform.email.data
        newsletter = NewsLetter(email, mongo)
        newsletter.save()

        return redirect(url_for("main.home"))

    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(
                    {"title": "Error", "message": f"Error in {field}:{error}"},
                    "error",
                )
    return render_template(
        "about.html",
        home="home",
        form=form,
        newsform=newsform,
        about_data=about_data,
        contact_data=contact_data,
        footer_data=footer_data,
    )


@main.route("/service", methods=["GET", "POST"])
def service():
    mongo = get_mongo(app)
    form = CustomerMessageForm()
    newsform = NewsLetterForm()
    slider_data = []
    for slider in mongo.slider.find():
        slider_data.append(
            {
                "title": slider.get("title"),
                "description": slider.get("description"),
                "contact_link": slider.get("contact_link"),
                "image": slider.get("image"),
                "quote_link": slider.get("quote_link"),
            }
        )
    print(slider_data)

    about_data = []
    for about in mongo.about.find():
        about_data.append(
            {
                "title": about.get("title"),
                "description": about.get("description"),
                "image": about.get("image"),
            }
        )

    team_data = []
    for team in mongo.team.find():
        team_data.append(
            {
                "name": team.get("name"),
                "description": team.get("description"),
                "image": team.get("image"),
                "link_fb": team.get("link_fb"),
                "link_tw": team.get("link_tw"),
                "link_linkedin": team.get("link_linkedin"),
                "link_insta": team.get("link_insta"),
            }
        )
    work_data = []
    for work in mongo.work.find():
        work_data.append(
            {
                "title": work.get("title"),
                "description": work.get("description"),
                "service_title": work.get("service_title"),
                "service_description": work.get("service_description"),
                "read": work.get("read"),
                "image": work.get("image"),
            }
        )

    contact_data = []
    for contact in mongo.contact.find():
        contact_data.append(
            {
                "telephone": contact.get("telephone"),
                "email": contact.get("email"),
            }
        )
    client_data = []
    for client in mongo.clients.find():
        client_data.append(
            {
                "title": client.get("title"),
                "description": client.get("description"),
                "service_title": client.get("client_title"),
                "service_description": client.get("client_description"),
                "read": client.get("read"),
                "image": client.get("image"),
            }
        )
        for client in client_data:
            print("client image:", client["image"])
    service_data = []
    for service in mongo.service.find():
        service_data.append(
            {
                "title": service.get("title"),
                "description": service.get("description"),
                "service_title": service.get("service_title"),
                "service_description": service.get("service_description"),
                "read": service.get("read"),

FlaskApp/seotech_app/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Panel</title>
    <link
      href="https://fonts.googleapis.com/css?family=JetBrains Mono"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/bootstrap.css') }}"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- fonts style -->
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/6en8XCp+HHAAK5GSLf2xlYtvJ8U2Q4U+9cuEnJoa3/ZD2Vr184mLl0aZ0qFJJEW"
      crossorigin="anonymous"
    />
    <!-- Custom styles for this template -->
    <link
      href="{{ url_for('static', filename='css/admin_.css') }}"
      rel="stylesheet"
    />
    {{ toastr.include_jquery() }} {{ toastr.include_toastr_css() }} {{
    toastr.message() }}
  </head>
  <body>
    {{ toastr.include_toastr_js() }} {%include 'admin_header.html'%} {% block
    content %}{% endblock %} {%include 'admin_footer.html'%}
  </body>

  <script
    type="text/javascript"
    src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"
  ></script>
  <script
    type="text/javascript"
    src="{{ url_for('static', filename='js/bootstrap.js') }}"
  ></script>
  <script
    type="text/javascript"
    src="{{ url_for('static', filename='js/custom.js') }}"
  ></script>
</html>

FlaskApp/seotech_app/templates/admin_content_update.html
{%extends 'admin_base.html'%} {%block content %}
<style>

</style>
<!-- Slider Table -->
<div class="admin-div slider-div">
  <h2 class="admin-h2">Sliders</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Contact_Link</th>
        <th>Image</th>
        <th>Quote_Link</th>
      </tr>
    </thead>
    <tbody>
      {% for slider in slider_data %}
      <tr>
        <td>{{ slider.title }}</td>
        <td>{{ slider.description }}</td>
        <td>{{ slider.contact_link }}</td>
        <td>{{ slider.image }}</td>
        <td>{{ slider.quote_link }}</td>
        <td>
          <form
            action="{{ url_for('admin_.admin_delete_slider', id=slider.id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_slider') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>

<!-- About Table -->
<div class="admin-div service-div">
  <h2 class="admin-h2">Service</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Image</th>
        <th>Read</th>
        <th>Service_Title</th>
        <th>Service_Description</th>
      </tr>
    </thead>

    <tbody>
      {% for service in service_data %}
      <tr>
        <td>{{ service.title }}</td>
        <td>{{ service.description }}</td>
        <td>{{ service.image }}</td>
        <td>{{ service.read }}</td>
        <td>{{ service.service_title}}</td>
        <td>{{ service.service_description }}</td>
        <td>
          <form
            action="{{ url_for('admin_.admin_delete_service', id=service.id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_service') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>
<div class="admin-div about-div">
  <h2 class="admin-h2">About</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Image</th>
        <th>Read</th>
      </tr>
    </thead>

    <tbody>
      {% for about in about_data %}
      <tr>
        <td>{{ about.title }}</td>
        <td>{{ about.description }}</td>
        <td>{{ about.image }}</td>
        <td>{{ about.read }}</td>

        <td>
          <form
            action="{{ url_for('admin_.admin_delete_about', id=about.id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_about') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>
<div class="admin-div work-div">
  <h2 class="admin-h2">Work</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Image</th>
        <th>Read</th>
        <th>Service_Title</th>
        <th>Service_Description</th>
      </tr>
    </thead>

    <tbody>
      {% for work in work_data %}
      <tr>
        <td>{{ work.title }}</td>
        <td>{{ work.description }}</td>
        <td>{{ work.image }}</td>
        <td>{{ work.read }}</td>
        <td>{{ work.service_title}}</td>
        <td>{{ work.service_description }}</td>

        <td>
          <form
            action="{{ url_for('admin_.admin_delete_work', id=work.id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_work') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>
<div class="admin-div team-div">
  <h2 class="admin-h2">Team</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Link_Fb</th>
        <th>Link_Tw</th>
        <th>Link_linkedin</th>
        <th>Link_İnsta</th>
        <th>Image</th>
        <th>Read</th>
      </tr>
    </thead>

    <tbody>
      {% for team in team_data %}
      <tr>
        <td>{{ team.name }}</td>
        <td>{{ team.description }}</td>
        <td>{{ team.image }}</td>
        <td>{{ team.link_fb }}</td>
        <td>{{ team.link_tw }}</td>
        <td>{{ team.link_linkedin }}</td>
        <td>{{ team.link_insta }}</td>

        <td>
          <form
            action="{{ url_for('admin_.admin_delete_team', id=team.id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_team') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>
<div class="admin-div client-div">
  <h2 class="admin-h2">Client</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Image</th>
      </tr>
    </thead>

    <tbody>
      {% for client in client_data %}
      <tr>
        <td>{{ client.name }}</td>
        <td>{{ client.description }}</td>
        <td>{{ client.image }}</td>

        <td>
          <form
            action="{{ url_for('admin_.admin_delete_client', id=client.id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_client') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>
<div class="admin-div contact-div">
  <h2 class="admin-h2">Contact</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Telephone</th>
        <th>Email</th>
      </tr>
    </thead>

    <tbody>
      {% for contact in contact_data %}
      <tr>
        <td>{{ contact.telephone }}</td>
        <td>{{ contact.email }}</td>

        <td>
          <form
            action="{{ url_for('admin_.admin_delete_contact', id=contact.id) }}" method="POST">
            <button class="admin-button delete-button" type="submit">Delete</button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_contact') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
  </table>
</div>
<div class="admin-div footer-div">
  <h2 class="admin-h2">Footer</h2>
  <table class="admin-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Link_Facebook</th>
        <th>Link_Twitter</th>
        <th>Link_Linkedin</th>
        <th>Link_Youtebe</th>
      </tr>
    </thead>

    <tbody>
      {% for footer in footer_data %}
      <tr>
        <td>{{ footer.title }}</td>
        <td>{{ footer.description }}</td>
        <td>{{ footer.link_facebook }}</td>
        <td>{{ footer.link_twitter }}</td>
        <td>{{ footer.link_linkedin }}</td>
        <td>{{ footer.link_youtube }}</td>

        <td>
          <form
            action="{{ url_for('admin_.admin_delete_footer', id=footer._id) }}"
            method="POST"
          >
            <button class="admin-button delete-button" type="submit">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
      <form action="{{ url_for('admin_.admin_content_update_footer') }}" method="POST">
        <button class="admin-button add-button" type="submit">Add</button>
      </form>
    </tbody>
  </table>
</div>
<!-- Repeat the above div for each of your other classes: Service, Work, Team, Client, Contact, Footer -->
<!-- Just replace 'about' with the class name in the div class and the h2 text, and 'edit_about' and 'delete_about' with the actual routes -->
{%endblock%}

FlaskApp/seotech_app/templates/admin_content_update_about.html
{% extends "admin_base.html" %}

{% block content %}
<section class="admin-section update-section">
  <div class="admin-container">
    <div class="admin-col">
      <div class="admin-div">
        <h2 class="admin-h2">Edit About Section</h2>

        <form
          action="{{ url_for('admin_.admin_content_update_about') }}"
          method="post"
          enctype="multipart/form-data"
        >
          {{ form.hidden_tag() }}
          {{ form.title.label }} {{ form.title() }}
          {{ form.description.label }} {{ form.description() }}
          {{form.read.label}} {{form.read()}}
          {{ form.image.label }} {{ form.image() }}
          <button class="admin-button" type="submit">Update About</button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

FlaskApp/seotech_app/templates/admin_content_update_footer.html
{% extends "admin_base.html" %} {% block content %}
<section class="admin-section update-section">
  <div class="admin-container">
    <div class="admin-col">
      <div class="admin-div">
        <h2 class="admin-h2">Edit Footer Section</h2>

        <form
          action="{{ url_for('admin_.admin_content_update_footer') }}"
          method="post"
          enctype="multipart/form-data"
        >
          {{ form.hidden_tag() }} {{ form.title.label }} {{ form.title() }} {{
          form.description.label }} {{ form.description() }} {{
          form.link_facebook.label }} {{ form.link_facebook() }} {{
          form.link_twitter.label }} {{ form.link_twitter() }} {{
          form.link_linkedin.label }} {{ form.link_linkedin() }} {{
          form.link_youtube.label }} {{ form.link_youtube() }}
          <button class="admin-button" type="submit">Update Footer</button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

FlaskApp/seotech_app/templates/admin_content_update_slider.html
{% extends "admin_base.html" %} {% block content %}
<section class="admin-section update-section">
  <div class="admin-container">
    <div class="admin-col">
      <div class="admin-div">
        <h2 class="admin-h2">Edit Slider Section</h2>

        <form
          action="{{ url_for('admin_.admin_content_update_slider') }}"
          method="post"
          enctype="multipart/form-data"
        >
          {{ form.hidden_tag() }} {{ form.title.label }} {{ form.title() }}
          {{form.description.label}}{{form.description()}}
          {{form.contact_link.label}}{{form.contact_link()}}{{form.quote_link.label}}{{form.quote_link()}}{{form.image.label}}{{form.image()}}
          <button class="admin-button" type="submit">Update Slide</button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

FlaskApp/seotech_app/templates/admin_content_update_team.html
{% extends "admin_base.html" %} {% block content %}
<section class="admin-section update-section">
  <div class="admin-container">
    <div class="admin-col">
      <div class="admin-div">
        <h2 class="admin-h2">Edit Team Section</h2>

        <form
          action="{{ url_for('admin_.admin_content_update_team') }}"
          method="post"
          enctype="multipart/form-data"
        >
          {{ form.hidden_tag() }} {{ form.name.label }} {{ form.name() }} {{
          form.description.label }} {{ form.description() }} {{ form.image.label
          }} {{ form.image() }} {{ form.link_fb.label }} {{ form.link_fb() }} {{
          form.link_tw.label }} {{ form.link_tw() }} {{ form.link_linkedin.label
          }} {{ form.link_linkedin() }} {{ form.link_insta.label }} {{
          form.link_insta() }}
          <button class="admin-button" type="submit">Update Team</button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

FlaskApp/seotech_app/templates/admin_header.html
<!-- Admin header section starts -->

<header class="admin_header_section">
  <div class="admin-header">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg custom_nav-container">
        <a
          class="navbar-brand"
          href="{{ url_for('admin_.admin_content_update') }}"
        >
          <span> Seotech </span>
        </a>

        <!-- Check if user is logged in -->
        <span class="nickname-label"></span>
        <!-- Display nickname -->
        <a href="{{ url_for('admin_.admin_logout') }}" class="logout-button"
          >Logout</a
        >
        <!-- Display logout button -->

        <a href="{{ url_for('admin_.admin_login') }}" class="login-button"
          >Login</a
        >
        <!-- Display login button -->

        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="s-1"> </span>
          <span class="s-2"> </span>
          <span class="s-3"> </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div
            class="d-flex mx-auto flex-column flex-lg-row align-items-center"
          >
            <ul class="navbar-nav">
              <li
                class="nav-item {% if 'admin_content_update' in request.endpoint %}active{% endif %}"
              >
                <a
                  class="nav-link"
                  href="{{ url_for('admin_.admin_content_update') }}"
                >
                  Content
                </a>
              </li>
              <li
                class="nav-item {% if 'admin_users' in request.endpoint %}active{% endif %}"
              >
                <a class="nav-link" href="{{ url_for('admin_.admin_users') }}">
                  Users
                </a>
              </li>
              <li
                class="nav-item {% if 'admin_messages' in request.endpoint %}active{% endif %}"
              >
                <a
                  class="nav-link"
                  href="{{ url_for('admin_.admin_messages') }}"
                >
                  Messages
                </a>
              </li>
              <li
                class="nav-item {% if 'admin_newsfeed' in request.endpoint %}active{% endif %}"
              >
                <a
                  class="nav-link"
                  href="{{ url_for('admin_.admin_newsfeed') }}"
                >
                  News
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>
<!-- Admin header section ends -->

FlaskApp/seotech_app/templates/admin_register.html
{% extends "admin_base.html" %} {% block content %}


<section class="admin-register-section">
  <div class="admin-container">
    <div class="admin-col">
      <div class="admin-div">
        <h2 class="admin-h2">Sign-Up</h2>
      <form action="{{ url_for('admin_.admin_register') }}" method="post">
         {{form.hidden_tag()}}
        <div class="admin-form">
         {{ form.email.label }}
         {{ form.email(class="admin-input", placeholder="Email:") }}
        </div>
        <div class="admin-form">
          {{ form.username.label }}
          {{ form.username(class="admin-input", placeholder="Username:") }}
         </div>
         <div class="admin-form">
          {{ form.name.label }}
          {{ form.name(class="admin-input", placeholder="Name:") }}
         </div>
        <div class="admin-form">
         {{ form.password.label }}
         {{ form.password(class="admin-input", placeholder="Password:") }}
        </div>
        <div class="admin-form">
          {{ form.confirm.label }}
          {{ form.confirm(class="admin-input", placeholder="Confirm:") }}
         </div>
        <button class="admin-button" type="submit">Sign Up</button>
      </div>
      </form>
    </div>
  </div>
</section>
{% endblock %}

     

FlaskApp/seotech_app/templates/admin_user_update.html
{% extends "admin_base.html" %} {% block content %}


<section class="admin-register-section">
  <div class="admin-container">
    <div class="admin-col">
      <div class="admin-div">
        <h2 class="admin-h2">Update User</h2>
        <form action="{{ url_for('admin_.admin_update_user', id=user_id, ) }}" method="post">
         {{form.hidden_tag()}}
        <div class="admin-form">
         {{ form.email.label }}
         {{ form.email(class="admin-input", placeholder=user.email) }}
        </div>
        <div class="admin-form">
          {{ form.username.label }}
          {{ form.username(class="admin-input", placeholder=user.username) }}
         </div>
         <div class="admin-form">
          {{ form.name.label }}
          {{ form.name(class="admin-input", placeholder=user.name) }}
         </div>
         <div class="admin-checkbox">
            {{ form.admin.label }}
            {{form.admin}}
        </div>
        <button type="submit" class="admin-button" action="{{url_for('admin_.admin_users')}}" >Update</button>
      </div>
      </form>
    </div>
  </div>
</section>
{% endblock %}

     

FlaskApp/seotech_app/templates/contact.html
{% block contact %}
<section class="contact_section layout_padding" id="contactLink">
  <div class="contact_section">
    <div class="container">
      <div class="heading_container">
        <h2>
          Get In touch
        </h2>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-8 mx-auto">
          <form action="{{url_for('main.about')}}" method="POST">
            <div class="form-row">
              <div class="form-group col-md-6">
               {{form.name}}
              </div>
              <div class="form-group col-md-6">
              {{form.email}}
              </div>

            </div>
            <div class="form-row">
              <div class="form-group col">
                {{form.subject}}
              </div>
            </div>
            <div class="form-group">
             {{form.email}}
            </div>
            <div class="d-flex justify-content-center">
              <button type="submit" class="">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  </section>
{% endblock %}

FlaskApp/seotech_app/templates/footer.html
{% block footer %}
  <section class="container-fluid footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </section>
{% endblock %}